alter system set processes = 200 scope = spfile;
alter system set sessions = 350 scope = spfile;
alter system set transactions = 380 scope = spfile;

CREATE TABLE "CSO_CENTROS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE)
   );
   ALTER TABLE "CSO_CENTROS" ADD CONSTRAINT "CSO_CENTROS_PK" PRIMARY KEY ("ID");
   ALTER TABLE "GDS_CSO"."CSO_CENTROS" MODIFY ("ID" NOT NULL ENABLE);

Insert into GDS_CSO.CSO_CENTROS (ID,NAME) values ('5316','GDS - CUSA');
Insert into GDS_CSO.CSO_CENTROS (ID,NAME) values ('17048','CSO Madrid');
Insert into GDS_CSO.CSO_CENTROS (ID,NAME) values ('8996','CSO Canarias');
Insert into GDS_CSO.CSO_CENTROS (ID,NAME) values ('9894','CSO Bilbao');
Insert into GDS_CSO.CSO_CENTROS (ID,NAME) values ('5147','CSO Barcelona');
Insert into GDS_CSO.CSO_CENTROS (ID,NAME) values ('16001','CSO Valencia');
Insert into GDS_CSO.CSO_CENTROS (ID,NAME) values ('11','CTI');
Insert into GDS_CSO.CSO_CENTROS (ID,NAME) values ('12','DOCOUT');
Insert into GDS_CSO.CSO_CENTROS (ID,NAME) values ('9883','CSO Sevilla');
Insert into GDS_CSO.CSO_CENTROS (ID,NAME) values ('5278','CSO Baleares');

CREATE TABLE "CSO_ESTATS" 
   (	"ID" NUMBER(10,0), 
	"DESCRIPCIO" VARCHAR2(400 BYTE), 
	"DESCRIPCIO_CA" VARCHAR2(400 BYTE), 
	"CODI" VARCHAR2(10 BYTE)
   );
CREATE UNIQUE INDEX "CSO_ESTATS_PK" ON "CSO_ESTATS" ("ID");
ALTER TABLE "CSO_ESTATS" MODIFY ("ID" NOT NULL ENABLE);

Insert into GDS_CSO.CSO_ESTATS (ID,DESCRIPCIO,DESCRIPCIO_CA,CODI) values ('2','Generada. Pendiente de validación','Generada. Pendent de validació','E1');
Insert into GDS_CSO.CSO_ESTATS (ID,DESCRIPCIO,DESCRIPCIO_CA,CODI) values ('3','Validada GDS. Pendiente de conformidad del proveedor','Validada GDS. Pendent de conformitat del proveedor','E2');
Insert into GDS_CSO.CSO_ESTATS (ID,DESCRIPCIO,DESCRIPCIO_CA,CODI) values ('4','Conforme','Conforme','E3');
Insert into GDS_CSO.CSO_ESTATS (ID,DESCRIPCIO,DESCRIPCIO_CA,CODI) values ('5','No conforme. Pendiente de resolver','No conforme.Pendent de resoldre','E4');
Insert into GDS_CSO.CSO_ESTATS (ID,DESCRIPCIO,DESCRIPCIO_CA,CODI) values ('6','Finalizada','Finalitzada','E5');
Insert into GDS_CSO.CSO_ESTATS (ID,DESCRIPCIO,DESCRIPCIO_CA,CODI) values ('7','Cancelada','Cancel·lada','E6');
Insert into GDS_CSO.CSO_ESTATS (ID,DESCRIPCIO,DESCRIPCIO_CA,CODI) values ('8','Incidencia en validación','Incidència validació','I1');
Insert into GDS_CSO.CSO_ESTATS (ID,DESCRIPCIO,DESCRIPCIO_CA,CODI) values ('9','Incidencia factura','Incidència factura','I2');


CREATE TABLE "GDS_CSO"."CSO_FACT_SRV" 
   (	"IDSRV" NUMBER(10,0), 
	"IDFACTURA" NUMBER(10,0)
   )

ALTER TABLE "GDS_CSO"."CSO_FACT_SRV" ADD CONSTRAINT "CSO_FACT_SRV_PK" PRIMARY KEY ("IDSRV", "IDFACTURA");
ALTER TABLE "GDS_CSO"."CSO_FACT_SRV" MODIFY ("IDSRV" NOT NULL ENABLE); 
ALTER TABLE "GDS_CSO"."CSO_FACT_SRV" MODIFY ("IDFACTURA" NOT NULL ENABLE);

CREATE TABLE "GDS_CSO"."CSO_FACTURAS" 
   (	"ID" NUMBER(10,0), 
	"FENTRADA" DATE, 
	"FULTIMESTAT" TIMESTAMP (6), 
	"IDCSO" NUMBER(10,0), 
	"MES_FACT" NUMBER(2,0), 
	"ANY_FACT" NUMBER(4,0), 
	"IDESTADO" NUMBER(1,0), 
	"IMPORTE" NUMBER(10,2), 
	"OBSERVACIONS" VARCHAR2(400 BYTE), 
	"CODE" VARCHAR2(20 BYTE)
   );
   
ALTER TABLE "GDS_CSO"."CSO_FACTURAS" ADD CONSTRAINT "CSO_FACTURAS_PK" PRIMARY KEY ("ID");
ALTER TABLE "GDS_CSO"."CSO_FACTURAS" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "GDS_CSO"."CSO_FACTURAS" MODIFY ("FENTRADA" NOT NULL ENABLE);

CREATE TABLE "GDS_CSO"."CSO_FACTURAS_FC" 
   (	"CODEFACTURA" VARCHAR2(200 CHAR), 
	"MONTH" NUMBER(2,0) DEFAULT 0, 
	"FC" NUMBER(10,2) DEFAULT 0.0
   );

ALTER TABLE "GDS_CSO"."CSO_FACTURAS_FC" ADD CONSTRAINT "CSO_FACTURAS_FC_PK" PRIMARY KEY ("CODEFACTURA", "MONTH");
ALTER TABLE "GDS_CSO"."CSO_FACTURAS_FC" MODIFY ("CODEFACTURA" NOT NULL ENABLE);
ALTER TABLE "GDS_CSO"."CSO_FACTURAS_FC" MODIFY ("MONTH" NOT NULL ENABLE);

 CREATE TABLE "GDS_CSO"."CSO_HIS_ESTATS" 
   (	"ID" NUMBER(10,0), 
	"IDFACTURA" NUMBER(10,0), 
	"IDESTAT" NUMBER(2,0), 
	"DATAESTAT" TIMESTAMP (6), 
	"ESTAT_ANTERIOR" NUMBER(2,0), 
	"DATA_ESTAT_ANTERIOR" TIMESTAMP (6), 
	"INCIDENCIA" VARCHAR2(400 BYTE)
   );
ALTER TABLE "GDS_CSO"."CSO_HIS_ESTATS" ADD CONSTRAINT "CSO_HIS_ESTATS_PK" PRIMARY KEY ("ID");
ALTER TABLE "GDS_CSO"."CSO_HIS_ESTATS" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "GDS_CSO"."CSO_HIS_ESTATS" MODIFY ("IDFACTURA" NOT NULL ENABLE);
ALTER TABLE "GDS_CSO"."CSO_HIS_ESTATS" MODIFY ("IDESTAT" NOT NULL ENABLE);
ALTER TABLE "GDS_CSO"."CSO_HIS_ESTATS" MODIFY ("DATAESTAT" NOT NULL ENABLE);
ALTER TABLE "GDS_CSO"."CSO_HIS_ESTATS" MODIFY ("DATA_ESTAT_ANTERIOR" NOT NULL ENABLE);

CREATE TABLE "GDS_CSO"."CSO_IMPORTS_PACTATS" 
   (	"IMPORTE" NUMBER(10,2), 
	"YEAR" NUMBER(10,0)
   );
ALTER TABLE "GDS_CSO"."CSO_IMPORTS_PACTATS" ADD CONSTRAINT "CSO_IMPORTS_PACTATS_PK" PRIMARY KEY ("YEAR");
ALTER TABLE "GDS_CSO"."CSO_IMPORTS_PACTATS" MODIFY ("IMPORTE" NOT NULL ENABLE); 
ALTER TABLE "GDS_CSO"."CSO_IMPORTS_PACTATS" MODIFY ("YEAR" NOT NULL ENABLE);

CREATE TABLE "GDS_CSO"."CSO_INC" 
   (	"ID" NUMBER, 
	"DESCRIPCIO" VARCHAR2(200 BYTE), 
	"DESCRIPCIO_ES" VARCHAR2(400 BYTE), 
	"TYPE_INC" VARCHAR2(40 BYTE)
   );
ALTER TABLE "GDS_CSO"."CSO_INC" ADD CONSTRAINT "CSO_INC_PK" PRIMARY KEY ("ID");
ALTER TABLE "GDS_CSO"."CSO_INC" MODIFY ("ID" NOT NULL ENABLE);

Insert into GDS_CSO.CSO_INC (ID,DESCRIPCIO,DESCRIPCIO_ES,TYPE_INC) values ('1','Incidencia 1','INCI ES 1','NOCONFORME');
Insert into GDS_CSO.CSO_INC (ID,DESCRIPCIO,DESCRIPCIO_ES,TYPE_INC) values ('2','Incidencia 2','Incidencia es 2','NOCONFORME');
Insert into GDS_CSO.CSO_INC (ID,DESCRIPCIO,DESCRIPCIO_ES,TYPE_INC) values ('3','Incidencia 3','Incidencia 3 es','NOCONFORME');
Insert into GDS_CSO.CSO_INC (ID,DESCRIPCIO,DESCRIPCIO_ES,TYPE_INC) values ('4','INCI VAL','INCI VAL','VALIDACIO');
Insert into GDS_CSO.CSO_INC (ID,DESCRIPCIO,DESCRIPCIO_ES,TYPE_INC) values ('5','INCI VAL2 ','IINCI VAL 2','VALIDACIO');
Insert into GDS_CSO.CSO_INC (ID,DESCRIPCIO,DESCRIPCIO_ES,TYPE_INC) values ('6','INCI VAL 3','INCI VAL 3','VALIDACIO');
Insert into GDS_CSO.CSO_INC (ID,DESCRIPCIO,DESCRIPCIO_ES,TYPE_INC) values ('7','INCI FACT 1','INCI FACT 1','FACTURACIO');
Insert into GDS_CSO.CSO_INC (ID,DESCRIPCIO,DESCRIPCIO_ES,TYPE_INC) values ('8','INIC FACT2','INCI FACT 2','FACTURACIO');
Insert into GDS_CSO.CSO_INC (ID,DESCRIPCIO,DESCRIPCIO_ES,TYPE_INC) values ('9','INCI FACT 3','INCI FACT 3','FACTURACIO');

CREATE TABLE "GDS_CSO"."CSO_MT_PARTIDA_FC" 
   (	"IDPARTIDA" NUMBER(10,0), 
	"MONTH" NUMBER(2,0), 
	"YEAR" NUMBER(10,0), 
	"FC" NUMBER(10,2)
   );
ALTER TABLE "GDS_CSO"."CSO_MT_PARTIDA_FC" MODIFY ("IDPARTIDA" NOT NULL ENABLE);

CREATE TABLE "GDS_CSO"."CSO_MT_PARTIDAS" 
   (	"ID" NUMBER(10,0), 
	"NOMLINEA" VARCHAR2(400 BYTE), 
	"IDSERVICIOS" VARCHAR2(400 BYTE)
   );

ALTER TABLE "GDS_CSO"."CSO_MT_PARTIDAS" ADD CONSTRAINT "CSO_MT_PARTIDAS_PK" PRIMARY KEY ("ID");
ALTER TABLE "GDS_CSO"."CSO_MT_PARTIDAS" MODIFY ("ID" NOT NULL ENABLE);

CREATE TABLE "GDS_CSO"."CSO_MT_PRECIOS" 
   (	"ID" NUMBER(10,0), 
	"IDCSO" NUMBER(10,0), 
	"IDSRV" NUMBER(10,0), 
	"TIPO" NUMBER(2,0)
   );
ALTER TABLE "GDS_CSO"."CSO_MT_PRECIOS" ADD CONSTRAINT "CSO_MT_PRECIOS_PK" PRIMARY KEY ("ID");

CREATE TABLE "GDS_CSO"."CSO_MT_PRECIOS_TR" 
   (	"IDPRECIO" NUMBER(10,0), 
	"NUMTRAM" NUMBER(4,0), 
	"VOLINI" NUMBER(10,2), 
	"VOLFIN" NUMBER(10,2), 
	"PRECIO" NUMBER(10,2)
   );
   
CREATE TABLE "GDS_CSO"."CSO_PART_SRV" 
   (	"IDSRV" NUMBER(10,0), 
	"IDPARTIDA" NUMBER(10,0), 
	"NOMSRV" VARCHAR2(400 BYTE)
   );
   
CREATE TABLE "GDS_CSO"."CSO_PARTIDAS_IMPORTS_PACTATS" 
   (	"IDPARTIDA" NUMBER(10,0), 
	"YEAR" NUMBER(4,0), 
	"IMPORTE" NUMBER(10,2) DEFAULT 0.00
   );

ALTER TABLE "GDS_CSO"."CSO_PARTIDAS_IMPORTS_PACTATS" ADD CONSTRAINT "CSO_PARTIDAS_IMPORTS_PACT_PK" PRIMARY KEY ("IDPARTIDA", "YEAR");
ALTER TABLE "GDS_CSO"."CSO_PARTIDAS_IMPORTS_PACTATS" MODIFY ("IDPARTIDA" NOT NULL ENABLE);
ALTER TABLE "GDS_CSO"."CSO_PARTIDAS_IMPORTS_PACTATS" MODIFY ("YEAR" NOT NULL ENABLE);

CREATE TABLE "GDS_CSO"."CSO_SRV_VOL" 
   (	"ID" NUMBER, 
	"IDCSO" NUMBER, 
	"IDSRV" NUMBER, 
	"VOLUM" NUMBER, 
	"MONTH" NUMBER, 
	"YEAR" VARCHAR2(20 BYTE), 
	"IMPORTE" NUMBER(10,2) DEFAULT 0.0
   );
ALTER TABLE "GDS_CSO"."CSO_SRV_VOL" MODIFY ("ID" NOT NULL ENABLE);

CREATE TABLE "GDS_CSO"."SYN_SRV" 
   (	"IDSRV" NUMBER(10,0), 
	"DESCRIP" VARCHAR2(200 BYTE)
   );
ALTER TABLE "GDS_CSO"."SYN_SRV" ADD CONSTRAINT "SYN_SRV_PK" PRIMARY KEY ("IDSRV");
ALTER TABLE "GDS_CSO"."SYN_SRV" MODIFY ("IDSRV" NOT NULL ENABLE);
ALTER TABLE "GDS_CSO"."SYN_SRV" MODIFY ("DESCRIP" NOT NULL ENABLE);


CREATE TABLE "GDS_CSO"."CSO" 
   (	
    "ID" NUMBER(10,0), 
	"IVA" NUMBER(2,0),
	"IGIC" NUMBER(2,0),
	"DESCUENTO" NUMBER(10,2), 
	"IMPUESTO" NUMBER(10,2), 
	"FACTURACIO" VARCHAR2(20 BYTE),
	"NRECURSOS" NUMBER(10,2),
	"PRECIO_RECURSO" NUMBER(10,2)
   );
   
ALTER TABLE "GDS_CSO"."CSO" ADD CONSTRAINT "CSO_PK" PRIMARY KEY ("ID");

CREATE SEQUENCE  "GDS_CSO"."S_ACT_MTUSUARIS"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 24 CACHE 20 ORDER  NOCYCLE ;
CREATE SEQUENCE  "GDS_CSO"."S_CSO_FACTURAS"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 246 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "GDS_CSO"."S_CSO_HIS_ESTATS"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 431 CACHE 20 ORDER  NOCYCLE ;
CREATE SEQUENCE  "GDS_CSO"."S_CSO_PARTIDAS"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 79 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "GDS_CSO"."S_CSO_PREUS"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 228 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "GDS_CSO"."S_CSO_SRV_VOL"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 70 CACHE 20 ORDER  NOCYCLE ;
 

 